blog_on_rails_with_authority/config/routes.rb
Rails.application.routes.draw do

  get('/', to:'posts#index', as: :root)

  resources :posts do
    resources :comments, only: [:create, :destroy], shallow: true
  end

  resources :users, except: [:show]
  post('user/:id/update_password', to:'users#update_pass', as: :update_user_password)

  resource :session, only: [:new, :edit, :create, :destroy]

end

blog_on_rails_with_authority/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.is_admin?
      can :manage, :all
    else
      can :read, :all
    end

    can :manage, Post do |post|
      post.user == user
    end

    can :manage, Comment do |comment|
      comment.user == user
    end

    can :manage, User do |valid_user|
      valid_user == user
    end
  end
end

blog_on_rails_with_authority/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog_on_rails_with_authority/app/models/comment.rb
class Comment < ApplicationRecord
belongs_to :user
belongs_to :post

validates :body, presence: true
end

blog_on_rails_with_authority/app/models/post.rb
class Post < ApplicationRecord
has_many :comments, dependent: :destroy
belongs_to :user

validates :title, presence: true, uniqueness: true
validates :body, presence: true, length: { minimum: 50 }



end

blog_on_rails_with_authority/app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :nullify
  has_many :comments, dependent: :nullify

  has_secure_password

  validates :first_name, :last_name, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: VALID_EMAIL_REGEX

  private

end

blog_on_rails_with_authority/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  helper_method :current_user

  def authenticate_user!
    unless current_user.present?
      flash[:alert] = 'Sign in first, bro'
      redirect_to new_session_path
    end
  end
end

blog_on_rails_with_authority/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :find_comment, only: [:destroy]
  before_action :authorize_user!, only: [:destroy]

  def create
    @post = Post.find params[:post_id]
    @comment = Comment.new comment_params
    @comment.post = @post
    @comment.user = current_user

    if @comment.save
      redirect_to post_path @post
    else
      redirect_to post_path @post
    end
  end

  def destroy
    @comment.destroy

    redirect_to post_path @comment.post.id
  end

  private

  def find_comment
    @comment = Comment.find params[:id]
  end

  def authorize_user!
    unless can?(:manage, @comment)
      flash[:alert] = "Access Denied"
      redirect_to post_path @comment.post
    end
  end

  def comment_params
    params.require(:comment).permit(:body)
  end

end

blog_on_rails_with_authority/app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
    end
    

end

blog_on_rails_with_authority/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]


  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params
    @post.user = current_user

    if @post.save
      redirect_to root_path
    else
      render :new
    end

  end

  def index
    @posts = Post.order(created_at: :desc)
  end

  def show
    @comment = Comment.new
    @comments = Post.find(params[:id]).comments.order(created_at: :desc)
  end

  def edit
  end

  def update
    if @post.update post_params
      redirect_to post_path @post.id
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

  def find_post
    @post = Post.find params[:id]
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def authorize_user!
    unless can?(:manage, @post)
      flash[:alert] = "Access Denied"
      redirect_to post_path @post
    end
  end
end

blog_on_rails_with_authority/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: session_params[:email])

    if @user&.authenticate(session_params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "Welcome, #{@user.first_name}"
      redirect_to root_path
    else
      flash.now[:alert] = 'Wrong email or password'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end


end

blog_on_rails_with_authority/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit]
  before_action :find_user, only: [:edit, :update, :update_pass]
  before_action :authorize_user!, only: [:edit, :update, :update_pass]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      flash[:notice] = "Welcome, #{@user.first_name}"
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update user_params
      flash[:notice] = 'Changes saved'
      redirect_to edit_user_path(@user)
    else
      flash[:alert] = 'Changes not saved'
      redirect_to edit_user_path(@user)
    end
  end

  def update_pass
    passwords = passwords_params

    if @user.authenticate(passwords[:current_password])
      if passwords[:current_password] == passwords[:password]
        flash[:alert] = "New password cannot be the same as current password"
      elsif passwords[:password].length < 6
        flash[:alert] = "Password needs to be at least 6 characters"
      elsif @user.update(password: passwords[:password], password_confirmation: passwords[:password_confirmation])
        flash[:notice] = "Password updated"
      else
        flash[:alert] = "Confirmation password does not match"
      end
    else
      flash[:alert] = "Current password is incorrect"
    end
    redirect_to edit_user_path(@user)
  end

  private

  def find_user
    @user = User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def passwords_params
    params.require(:password_change).permit(:current_password, :password, :password_confirmation)
  end

  def authorize_user!
    unless can?(:manage, @user)
      flash[:alert] = "Access Denied"
      redirect_to root_path
    end
  end
end

blog_on_rails_with_authority/app/helpers/application_helper.rb
module ApplicationHelper
end

blog_on_rails_with_authority/app/helpers/home_helper.rb
module HomeHelper
end

blog_on_rails_with_authority/app/helpers/posts_helper.rb
module PostsHelper
end

blog_on_rails_with_authority/app/views/home/index.html.erb
<h1> Welcome Page</h1>

blog_on_rails_with_authority/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogOnRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <nav class="nav-bar navbar-expand-sm">
      <%= link_to 'Blog On Rails', root_path, id: "nav-logo" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
          <span class="navbar-toggler-icon">🔽</span>
        </button>

      <div id="navbarNav" class="collapse navbar-collapse">
        <div class="navbar-nav">
          <%= link_to 'Home', root_path %>
          <%= link_to 'New Post', new_post_path %>
          <% if current_user.present?%>
            <%= link_to "#{current_user.first_name}", edit_user_path(current_user.id) %>
            <%= link_to 'Sign Out', session_path, method: :delete %>
          <% else %>
            <%= link_to 'Sign In', new_session_path %>
            <%= link_to 'Sign Up', new_user_path %>
          <% end %>
        </div>
      </div>
    </nav>
    <div class="container-fluid webpage-container">
      <% if flash[:notice] %>
        <div class="alert alert-success" role="alert">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-warning" role="alert">
          <%= flash[:alert] %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

blog_on_rails_with_authority/app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.present? %>
    <p><%= @post.errors.full_messages.join(', ') %> </p>
  <% end %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control"%>
  </div>

  <div>
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control"%>
  </div>

  <%= f.submit class: "btn btn-outline-primary" %>
  <%= link_to 'Cancel', post_path(@post) %>
<% end %>

blog_on_rails_with_authority/app/views/posts/index.html.erb
<div class="row">
  <% @posts.each do |post| %>
    <div class="col-lg-4 col-md-6 col-sm-12">
      <div class="card container">
        <div class="post-title">
          <h4><%= link_to "#{post.title}", post_path(post.id) %></h4>
        </div>
        <div class="post-body"
          <p><%= post.body %></p>
        </div>
        <%= link_to "#{post.comments.count} comment#{'s' if post.comments.count > 1}", post_path(post.id), class: "comments-link" %>
      </div>
    </div>
  <% end %>
</div>

blog_on_rails_with_authority/app/views/posts/new.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.present? %>
    <p><%= @post.errors.full_messages.join(', ') %> </p>
  <% end %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control"%>
  </div>

  <div>
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control"%>
  </div>

  <%= f.submit class: "btn btn-outline-primary"%>
    <%= link_to 'Cancel', root_path %>
<% end %>

blog_on_rails_with_authority/app/views/posts/show.html.erb
<div class="post-title">
  <h1><%= @post.title %></h1>
</div>
<div class="post-body"
  <p><%= @post.body %></p>
</div>
<small>Posted <%= time_ago_in_words(@post.created_at) %> ago by <strong><%= @post.user.first_name %> <%= @post.user.last_name %></strong></small><br>
<% if can?(:manage, @post) %>
  <%= link_to 'Edit', edit_post_path(@post.id), class:"btn btn-outline-primary" %>
  <%= link_to 'Delete', post_path(@post.id), class:"btn btn-outline-primary", method: :delete, data: { confirm: 'Are you sure?'} %>
<% end %>
  <h3>Comment</h3>
  <%= form_for @comment, url: post_comments_path(@post) do |f| %>
    <%= f.text_area :body, class: "form-control", placeholder: "What's on your mind?" %>
    <%= f.submit 'Submit', class:"btn btn-outline-primary" %>
  <% end %>
  <div class="answer-list">
    <div class="answer-list-item">
      <% @comments.each do |comment| %>
      <p><%= comment.body %></p>
      <small>Commented <%= time_ago_in_words(comment.created_at) %> ago by <strong><%= comment.user.first_name %> <%= comment.user.last_name %></strong></small>
      <% if can?(:manage, comment) %>
        • <%= link_to 'Delete', comment_path(comment.id), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
      <hr>
      <% end %>
    </div>
  </div>

blog_on_rails_with_authority/app/views/users/edit.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.present? %>
    <p><%= @user.errors.full_messages.join(', ') %> </p>
  <% end %>

  <div>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, class: "form-control"%>
  </div>

  <div>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, class: "form-control"%>
  </div>

  <div>
    <%= f.label :email %><br>
    <%= f.email_field :email, class: "form-control"%>
  </div>


  <%= f.submit 'Save Changes', class: "btn btn-outline-primary"%>
  <%= link_to 'Cancel', edit_user_path(@user) %>
<% end %>

<button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#password-form">
  Change Password
</button>

<div class="collapse" id="password-form">
  <%= form_for :password_change, url: update_user_password_path  do |f| %>

    <div>
      <%= f.label "Current Password" %><br>
      <%= f.password_field :current_password, class: "form-control"%>
    </div>

    <div>
      <%= f.label "New Password" %><br>
      <%= f.password_field :password, class: "form-control"%>
    </div>

    <div>
      <%= f.label "New Password Confirmation"  %><br>
      <%= f.password_field :password_confirmation, class: "form-control"%>
    </div>
    <%= f.submit 'Update Password', class: "btn btn-outline-primary"%>
    <%= link_to 'Cancel', edit_user_path(@user) %>

  <% end %>
<div>

blog_on_rails_with_authority/app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.present? %>
    <p><%= @user.errors.full_messages.join(', ') %> </p>
  <% end %>

  <div>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, class: "form-control"%>
  </div>

  <div>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, class: "form-control"%>
  </div>

  <div>
    <%= f.label :email %><br>
    <%= f.email_field :email, class: "form-control"%>
  </div>

  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password, class: "form-control"%>
  </div>

  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation, class: "form-control"%>
  </div>

  <%= f.submit 'Sign Up', class: "btn btn-outline-primary"%>
    <%= link_to 'Cancel', root_path %>
<% end %>